[project]
name = "odoo-apps-partner-contact"
version = "19.0.20260528.1"
dependencies = [
    "odoo-addon-calendar_partner_link==19.0.*",
    "odoo-addon-crm_link==19.0.*",
    "odoo-addon-crm_partner_link==19.0.*",
    "odoo-addon-crm_partner_multi_relation==19.0.*",
    "odoo-addon-partner_email_history==19.0.*",
    "odoo-addon-partner_link==19.0.*",
    "odoo-addon-sale_partner_link==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
